export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        clinical: {
          primary: '#1D4ED8',
          'primary-light': '#DBEAFE',
          'primary-dark': '#1E3A8A',
          bg: '#F8FAFC',
          surface: '#FFFFFF',
          border: '#E2E8F0',
          'text-primary': '#0F172A',
          'text-secondary': '#475569',
          'text-muted': '#94A3B8',
          auto: '#16A34A',
          'auto-bg': '#DCFCE7',
          hitl: '#D97706',
          'hitl-bg': '#FEF3C7',
          verified: '#1D4ED8',
          'verified-bg': '#DBEAFE',
          final: '#7C3AED',
          'final-bg': '#EDE9FE',
          critical: '#DC2626',
          'critical-bg': '#FEE2E2',
          warning: '#D97706',
          normal: '#16A34A',
          offline: '#6B7280',
          'offline-bg': '#F3F4F6',
        },
      },
    },
  },
  plugins: [],
}
